### ISSUE TITLE
Set center view on Android ? 

### ISSUE THREAD

**Issue by shopmium** [yomybaby/kr.yostudio.drawer#2]
Hi, 
I have installed kr.yostudio.drawer widget with com.tripvi.drawerlayout module.
Actually, we cannot update center view because "setCenterView" method from module is not exposed.

First, I have added container view in "centerWindow" with update method for set the content view.

But, this solution doesn't work with Google Maps. The drawerlayout module handles this case.
Solution, for update center view on Android :

``` javascript
DrawerLayout.prototype.setCenterView = function(view){
    if (OS_ANDROID && view) {
      this.drawer.setCenterView(view);
    }
};
```

in my project :

``` javascript
#CoffeeScript
drawerLayout = Alloy.createWidget('kr.yostudio.drawer')
mapView = require('ti.map').createView()
$.sections.addEventListener 'itemclick', (event) =>
   drawerLayout.setCenterView(mapView) if event.itemIndex is 1
...


```

**Comment by yomybaby** [comment]
Thanks.

Also you can setCenterView directly.

```
// only android
drawerLayout.drawer.setCenterView(view)
```

On iOS, you can handle with centerWindow. because centWindow stay as window on iOS. 
But android, centerwindow doesn't use it anymore. See below code

https://github.com/yomybaby/kr.yostudio.drawer/blob/master/app/widgets/kr.yostudio.drawer/controllers/widget.js#L47-L81

It's little unusual. But I just want same method in iOS and Android. I'll try to make better to use.
But these day, I'm so busy.

This widget is a very early version. There are many thing to improve.
If you have any idea, please make a issue or PR.
Welcome to any suggest and any PR.

**Comment by arnaudbesnier** [comment]
Yes that's what we finally did for our Android app.
It works!

**Comment by nuno** [comment]
@yomybaby can you please give me a example to instead the open a new window when you click in the menu update the center with a view instead?

```
 $.index.drawerLayout.centerWindow(Alloy.createController('smile').getView());
VS
$.index.open(Alloy.createController('smile').getView());
```

Im missing something here, is for ios and android, thanks.

**Comment by yomybaby** [comment]
@nuno I just pushed some code. Now, setSenterView available. :smile:

**Comment by nuno** [comment]
@yomybaby I will test asap, you are awesome!

**Comment by nuno** [comment]
@yomybaby working great! Thank you for that!

**Comment by yomybaby** [comment]
:+1:
